config/routes.rb
Siya::Application.routes.draw do

  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/contact"
  devise_for :users
  resources :galleries do
    resource :gposts do
      root "gposts#index"
      end
  end
  resources :portfolios do
    resource :posts
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :post
  has_attached_file :asset, path: (Rails.root + "files/:id").to_s, url: "/files/:id",
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_attached_file :photo,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  has_attached_file :image,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  has_many :gposts
   validates_presence_of :name, uniqueness:true
  #default_scope order: "gallery.created_at DESC"
end

app/models/gpost.rb
class Gpost < ActiveRecord::Base
  has_attached_file :photo,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  has_attached_file :image,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  default_scope order: 'gposts.created_at DESC'
  belongs_to :gallery
  validates_presence_of :photo
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_attached_file :pic,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  validates :name,  presence: true, uniqueness: true

  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  has_attached_file :photo,
                    :storage=> :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  #has_attached_file :asset
  has_many :assets
  accepts_nested_attributes_for :assets

  validates_presence_of(:name)
  validates_uniqueness_of(:name)
  belongs_to :portfolio
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: false, uniqueness: false


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_filter :set_gallery, only: [:show, :edit, :update, :destroy]

  def index
  @galleries = Gallery.all.reverse_order
  @gposts = Gpost.all.limit(30)
  end

  def new
    @gallery = Gallery.new
  end
  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      flash[:success] = "New Photo added to Gallery"
      redirect_to @gallery
    else
      redirect_to :back
    end
  end
  def show

  end
private
  def gallery_params
    params.require(:gallery).permit!
  end
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end
end

app/controllers/gposts_controller.rb
class GpostsController < ApplicationController
  before_filter :find_gallery
  before_filter :find_gpost, only: [:show, :edit, :update, :destroy]

  def index
    @gposts = @gallery.gposts.all
  end

  def new
    @gpost = @gallery.gposts.new
  end

  def create
    @gpost = @gallery.gposts.build(gpost_params)
    if @gpost.save
      flash[:success] = "Picture Added to this Gallery "
      redirect_to gallery_gposts_url
    else
      redirect_to :back
    end
  end

  def show
  end

  def edit

  end
  def update

  end

  def find_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end
  def gpost_params
    params.require(:gpost).permit!
  end
  def find_gpost
    @gpost = @gallery.gposts.find(params[:id])
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_action :find_post, only: [:show]

  def index
       @ports = Portfolio.all

  end

  def new
      @port = Portfolio.new
  end

  def create
    @port = Portfolio.new(user_params)
    if @port.save
      flash[:success] = "portfolio created"
      redirect_to portfolios_path
    else
      render 'portfolios/new'
    end
  end
  def show
    #@post = @port.posts.find(params[:portfolio_id])
    # render 'posts/show'
  end
     def edit

     end
  def update

  end
  def destroy

  end
 private
  def set_portfolio
    @port = Portfolio.find(params[:id])
  end
   def find_post
     @post = @port.posts.find(params[:id])
   end
  def user_params
    params.require(:portfolio).permit! #not safe though
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :find_portfolio
  before_filter :find_post, only: [:edit, :update]

  def index

  end

  def new
    @post = @port.posts.build
    #3.times { @post.assets.build}
  end

  def create
    @post = @port.posts.build(post_params)
     if @post.save
      flash[:success] = "new service created"
      redirect_to portfolio_posts_path
    else
      render :new
    end
  end

  def show
     	#redirect_to root_path
   @all_posts = @port.posts.all
  end
  def update
  end


  def edit

  end
    def destroy
     # @post =  @port.posts.find(params[:id])
     #@post.destroy
     # flash[:notice] = "Picture has been deleted"
     # redirect_to root_path
    end
 private

   def find_portfolio
     @port = Portfolio.find(params[:portfolio_id])
   end

  def find_post
    @post = @port.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit!
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def photo_for(post)
    image_tag post.photo.url if post.photo?
  end

  def video_for(post)
    video_tag(post.image.url, controls: true, autobuffer: true) if post.image?
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gposts_helper.rb
module GpostsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/galleries/index.html.erb
<div id="contents">
<h2>Latest Pictures In Gallery</h2>
  <h2 class="rig">
   <%= link_to 'Create Gallery Folder', new_gallery_path if signed_in?%>
  </h2>
<div class="sidebar">
<% @galleries.each do |g| %>


    <pre><h2><%= link_to g.name, gallery_gposts_path(g) %></h2>
   Made: <%= time_ago_in_words(g.created_at) %> ago</pre>
    <%# photo_for(g) %>

<% end %>
</div>
<div class="main">
  <ul class="news">
  <% @gposts.each do |gp| %>
     <div class="thum"> <%= link_to photo_for(gp), gallery_gposts_path(gp.gallery) %>
     </div>

  <% end %>
  </ul>
</div>
</div>

app/views/galleries/new.html.erb
<div class="row">
  <div class="span5 offset4">
<%= form_for(@gallery) do |f| %>
        <%= f.label :name  %>
        <%= f.text_field :name %>

        <%= f.label :desc, "More Info About This Folder" %>
        <%= f.text_field :desc %>
   <%#render 'shared/field', f:f %>
    <%= f.submit  "Create Gallery Folder" %>
<% end %>
      </div>
    </div>

app/views/gposts/index.html.erb
<span>
<h2><%= "#{@gallery.name.capitalize}" %> Gallery</h2>
<span class="right"><%= link_to "Add Picture or Video to Gallery",new_gallery_gposts_path(@gallery) %></span>
</span>
<% @gposts.each do |gp|  %>
    <div>
   <span class="image "> <%= photo_for(gp) %></span>
    <span class="video"><%= video_for(gp) %></span>
    <p class="lim"><%= gp.name %></p>
    </div>
<% end %>

app/views/gposts/new.html.erb
<%= form_for [@gallery, @gpost] do |f|  %>
    <%= render 'shared/field', f:f  %>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>PhotoLigne <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="content">

<%= render 'shared/header' %>
<% flash.each do |key, value| %>
    <div class="flash" id="<%= key %>" >
    <%= value %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/portfolios/index.html.erb
<h1>Our Services</h1>
 <p >
<% @ports.each do |port| %>

    <div class="data">
<h1><%= link_to(port.name, portfolio_posts_path(port)) %></h1>

<%= port.desc %>
    </div>
<%# port.nopic  %>
    </p>
<% end %>

app/views/portfolios/new.html.erb
<%= provide(:title, "| Create an Event") %>
<%= form_for(@port) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :desc, "description" %>
<%= f.text_area :desc %>

   <%= f.submit "Create Event" %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<div class="row">
  <div class="span5 offset4">
<%= form_for([@port, @post], html: {multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= render 'shared/field', f:f %>

    <%= f.submit %>
<% end %>
      </div>
    </div>

app/views/posts/show.html.erb
<% name = @port.name%>
<%= provide(:title, "| #{name}") %>
<div class="main">
  <div class="image ">
<%= name.capitalize! %> Photos and Videos
<%= link_to "Add New Photos and Video to #{name}", new_portfolio_posts_path if signed_in? %>




<% @all_posts.each do |p| %>

    <%= photo_for(p) %>
        <p>
    <%= video_for(p) %>
        </p>
     <p class="lim">
       Info: <%= p.name %>
     </p>
     <%# link_to("delete", [@port,p.destroy], remote: true,  method: :delete) %>
<% end %>
 </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-error">
The form has <%= pluralize(object.errors.count, "error") %> 
</div>
	<ul> 
		<% object.errors.full_messages.each do |msg| %>
			<li>*  <%= msg %></li>
			<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_field.html.erb
<%# number = 0 %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :photo, "Picture" %>
<%= f.file_field :photo  %>
<%= f.label :image, "Video" %>
<%= f.file_field :image %>
<%# f.fields_for :assets do |asset| %>
    <%# asset.label :asset, "Video or Picture ##{number += 1} "%>
    <%# asset.file_field :asset  %>
<%# end %>

app/views/shared/_header.html.erb
<div id="header">
  <h1 class="cen">
  <%= link_to("PhotoLigne", root_path) %>
  </h1>
    <div class="cenli">
      <li>
        <%= link_to("Home", root_path)  %>
        <%= link_to("Services", portfolios_path)  %>
        <%= link_to("Gallery", galleries_path) %>
      <%= link_to("Contact Us", static_pages_contact_path) %>

<% if(user_signed_in?)  %>
    <%= current_user.email %>
    <%= link_to("Sign Out", destroy_user_session_path, method: :delete)  %>
<% else %>
    <%= link_to("Sign in", new_user_session_path)  %>
<% end %>
      </li>
    </div>
</div>

app/views/static_pages/contact.html.erb
<%= provide(:title, "| Contact Us") %>
<h1>Our Contact Details</h1>
<p class="hero-unit">business card goes here </p>

app/views/static_pages/home.html.erb
<% provide(:title, " | Home ") %>
<p class="rig"><%= link_to 'Add New Photos and Videos to Gallery', new_gallery_path if signed_in?%></p>
<h2 class="hero-unit">Photoligne is a professional Photo taking Service
 for Weddings, Special Events, in fact, we Do Any Event that is Too Good to Be Forgotten  </h2>